### ISSUE TITLE
Questions about second server

### ISSUE THREAD

**Issue by Teberon** [DrPsychick/ark-server-charts#1] opened 2021-04-12 07:27 UTC
I am sorry if this isn't the right place. I found your helm chart and after two days fiddling around, I got my first server up. I just have a few questions as it doesn't run the way I think it should.
1. I set custom .ini files as here for testing https://artifacthub.io/packages/helm/ark-server-charts/ark-cluster/0.0.14 and added server password and maxplayers and it doesn't take these values
2. there is no way to name the server? It shows up as Ark #12345 instead of a name I gave in nameoverride. Do I need to take fullnameoveride?
3. mods are not installed, I put 731604991 it says it is not available, seems to download it and then provides an error
4. what user is being used, is it possible to specify one to avoid issues with permissions?
5. tried to create second server, but getting error message when I use "queryudp: 27015 / gameudp: 7770 / rcon: 32330" (different ports given)
6. getting an error with the server even though it is running
Warning  Unhealthy         38m (x16 over 41m)  kubelet            Startup probe failed: dial tcp 10.42.0.173:32330: connect: connection refused

That should be all for now. Thanks in advance.

**Comment by DrPsychick** [comment] 2021-04-12 17:28
Hi @Teberon 

> I am sorry if this isn't the right place. I found your helm chart and after two days fiddling around, I got my first server up. I just have a few questions as it doesn't run the way I think it should.

It is the right place. Thanks for reaching out and congraz to your first running server :)

> 1. I set custom .ini files as here for testing https://artifacthub.io/packages/helm/ark-server-charts/ark-cluster/0.0.14 and added server password and maxplayers and it doesn't take these values

Yes. If you use custom `.ini` files, you must set these settings directly in the file.
If you have an idea how to render these variables in a user provided string, let me know. I'd love to add it.

> 2. there is no way to name the server? It shows up as Ark #12345 instead of a name I gave in nameoverride. Do I need to take fullnameoveride?

`sessionName` should set the name, see https://github.com/DrPsychick/ark-server-charts/blob/082ff1c475e1e33eba46b56a803f0347d14b2bea/charts/ark-cluster/templates/deployment.yaml#L131

> 3. mods are not installed, I put 731604991 it says it is not available, seems to download it and then provides an error

please, if this is reproducible, open a separate ticket for this error and provide details. If you use `latest` or `focal` of the base image, try `bionic` instead. There is no official `steamcmd` version for focal yet.

> 4. what user is being used, is it possible to specify one to avoid issues with permissions?

It uses user `steam` with UID `1000`. This comes from the base image: https://github.com/DrPsychick/arkserver/blob/master/Dockerfile

Using a different user would require either a different docker image or a mapping -> I would also see this as a separate issue, I hope someone can contribute.

> 5. tried to create second server, but getting error message when I use "queryudp: 27015 / gameudp: 7770 / rcon: 32330" (different ports given)

Please provide more details to this, how are your servers ports configured? How do you try to access the ports? 
As in the notes: each server needs its own ports.

> 6. getting an error with the server even though it is running
>    Warning  Unhealthy         38m (x16 over 41m)  kubelet            Startup probe failed: dial tcp 10.42.0.173:32330: connect: connection refused

For multiple servers, you MUST set ports for each server, see https://github.com/DrPsychick/ark-server-charts/blob/082ff1c475e1e33eba46b56a803f0347d14b2bea/charts/ark-cluster/values.yaml#L113

The RCON port is used in the liveness probe, so it must be activated on that port: https://github.com/DrPsychick/ark-server-charts/blob/082ff1c475e1e33eba46b56a803f0347d14b2bea/charts/ark-cluster/templates/deployment.yaml#L203

> That should be all for now. Thanks in advance.

Thanks for reaching out! Drop me a note/mail if you want to join the slack channel to chat (quicker than here)

**Comment by Teberon** [comment] 2021-04-13 10:09
I have set three servers with the following ports
servers:

      queryudp: 27015
      gameudp: 7770
      rcon: 32331

      queryudp: 27016
      gameudp: 7772
      rcon: 32332

      queryudp: 27017
      gameudp: 7774
      rcon: 32333

all three have different ports, but still the final check is incomplete

Unhealthy (22) | 3.5 mins ago | Startup probe failed: dial tcp 10.42.0.233:32331: connect: connection refused
-- | -- | --

Unhealthy (18) | 4.5 mins ago | Startup probe failed: dial tcp 10.42.0.231:32332: connect: connection refused
-- | -- | --


Unhealthy (22) | 4.2 mins ago | Startup probe failed: dial tcp 10.42.0.232:32333: connect: connection refused
-- | -- | --


Also there seems to be an issue with the PID
2021-04-13 09:57:39: Running /arkserver/ShooterGame/Binaries/Linux/ShooterGameServer Extinction\?ServerPassword=XYZ\?GameModIds=7.31604991e+08\?MaxPlayers=10\?RCONEnabled=True\?ServerAdminPassword=k3yb04rdc4t\?AltSaveDirectoryName=SavedArks\?SessionName=Teberon\'s\ Extinction\?QueryPort=27017\?Port=7774\?RCONPort=32333\?listen -clusterid=arkcluster -log
--
Tue, Apr 13 2021 11:57:39 am | 2021-04-13 09:57:39: Server PID: 81
Tue, Apr 13 2021 11:57:42 am | [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Tue, Apr 13 2021 11:57:43 am | Setting breakpad minidump AppID = 346110
Tue, Apr 13 2021 11:57:44 am | 2021-04-13 09:57:44: Bad PID ''; expected '81'

This is visible in all three logs (with different PID though)

**Comment by DrPsychick** [comment] 2021-04-13 20:54
Ok, so if you share the `ShooterGame/Saved` directory between the servers, then the PID gets overwritten when starting a second server. That might cause the issue of having a wrong PID.

As for the configuration. 
Check the `configmap` created with `kubectl get cm -o yaml`. You can also open a shell in the container and check the `/arkconfig` directory, the files will be mounted there. 

`arkmanager` will actually copy the `.ini` files into the game directory because they are, by default, set as ENV variable: https://github.com/DrPsychick/ark-server-charts/blob/082ff1c475e1e33eba46b56a803f0347d14b2bea/charts/ark-cluster/templates/deployment.yaml#L157

I hope this helps.

**Comment by DrPsychick** [comment] 2021-04-17 20:25
for the record: configuration issue was solved by @Teberon : https://github.com/DrPsychick/ark-server-charts/pull/4

Apart from that, if you got everything to work and have no more questions @Teberon , you can close this issue... unless you're too busy fighting dinos 😅

**Comment by DrPsychick** [comment] 2021-06-13 10:41
stale -> closed

**Closed by DrPsychick** 2021-06-13 10:41 UTC
Labels: question
